### ISSUE TITLE
Stop selenium after "java -jar selenium.jar > /dev/null &"???

### ISSUE THREAD

**Issue by sensorario** [Behat/MinkExtension-example#9]
I've written this script:

```
#!/bin/bash
# Run tests
java -jar selenium.jar > /dev/null &
./bin/behat
```

But sometimes I get this error:

```
03:01:26.748 WARN - Failed to start: SocketListener0@0.0.0.0:4444
Exception in thread "main" java.net.BindException: Selenium is already running on port 4444. Or some other service is.
at org.openqa.selenium.server.SeleniumServer.start(SeleniumServer.java:491)
at org.openqa.selenium.server.SeleniumServer.boot(SeleniumServer.java:300)
at org.openqa.selenium.server.SeleniumServer.main(SeleniumServer.java:245)
at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:93)
```

Exists a way to stop Selenium after tests?

**Comment by stof** [comment]
find the pid of the java process (with `ps aux` for instance) and kill it
